export const UsersActionTypes ={
    ADD_USER_START:"ADD_USER_START",
    ADD_USER_SUCCESS:"ADD_USER_SUCCESS",
    ADD_USER_FAILURE:"ADD_USER_FAILURE",
    GET_USER_START:"GET_USER_START",
    GET_USER_SUCCESS:"GET_USER_SUCCESS",
    GET_USER_FAILURE:"GET_USER_FAILURE",
}