export const ProductsActionTypes ={
    GET_PRODUCTS_START:"GET_PRODUCTS_START",
    GET_PRODUCTS_SUCCESS:"GET_PRODUCTS_SUCCESS",
    GET_PRODUCTS_FAILURE:"GET_PRODUCTS_FAILURE",
    GET_PRODUCT_START:"GET_PRODUCT_START",
    GET_PRODUCT_SUCCESS:"GET_PRODUCT_SUCCESS",
    GET_PRODUCT_FAILURE:"GET_PRODUCT_FAILURE",
}